### PR TITLE
Add zip64 extensions to enable large file restores

### PR DESCRIPTION
**Pull request by slarti5191**
Allows burpui to zip and restore files > 2GB

### CODE REVIEW

**Comment by ziirish** [comment]
Hello,

Thanks for the patch.

Could you give me more details about the usecase please?
This option is not enabled by default because it brings some incompatibilities with the zip/unzip binary provided in Linux distributions.

What tool can we use instead?

**Comment by ziirish** [comment]
up?

Would an option/switch to enable this feature at restoration time be an acceptable solution?

**Comment by slarti5191** [comment]
Hi,

Sorry for the lag getting back to you.

The use case is twofold:  
1) the default archive format is zip (easy enough to change).
2) We have admins that will be performing restores to Windows systems - it is possible for them to extract a tar, but the path of least resistance (for me) is to have zip "just work".

I've tested on a few Linux distributions and haven't run into any compatibility issues, but obviously there are a lot of variables there.

That said I think an option at restoration time would be a perfectly fine solution.

**Comment by ziirish** [comment]
Thank you for the feedback.

I'll merge your request and implement the switch so this option remains opt-in while I'm running some tests in order to decide weither we can make it default or not.

**Comment by ziirish** [comment]
Done [here](https://git.ziirish.me/ziirish/burp-ui/issues/97)

**Pull request merged**
